# Generated by Django 3.2.6 on 2021-08-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_format',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='item_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
