# Generated by Django 3.2.6 on 2021-08-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210819_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='item_format',
            new_name='product_format',
        ),
    ]
