# Generated by Django 3.2.6 on 2021-08-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210822_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='photo',
        ),
        migrations.AddField(
            model_name='release',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
